# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A59pmDM0KBNxWSPAYIbYfALZ1stz1o-q
"""

import numpy as np

import pandas as pd

import matplotlib.pyplot as plt

import seaborn as sns

data=pd.read_csv('/content/Crop_recommendation (1).csv')

data.head()

data.info()

